title: VIS Conference Deadlines # (Maintained by @abhshkdz)
email: rafa.veras@outlook.com
description: Countdowns to top VIS conference deadlines
author: Rafael Veras

domain: "rafaveguim.github.io"
baseurl: "vis-deadlines"

twitter_username: rafaveguim
twitter_hashtag: #vis
github_username: rafaveguim
github_repo: vis-deadlines

markdown: kramdown
ga_id: UA-36274081-2

theme: jekyll-theme-minimal
